#pragma once

#define RGBLIGHT_LED_COUNT 12
#define WS2812_DI_PIN GP0

#define OLED_DISPLAY_128X32
#define OLED_IC OLED_IC_SSD1306

#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_STATIC_GRADIENT

#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define MATRIX_ROWS 3
#define MATRIX_COLS 3